name: Jira Release Web Hook
description: Creates a new Jira release and assigns all relevant issues to it.
inputs:
  jira-project-key:
    description: "Jira project identifier"
    required: true
  jira-automation-webhook:
    description: "Jira automation webhook url"
    required: true
  build-version:
    description: "Version identifier"
    required: true
runs:
  using: composite
  steps:
    - name: Update Locale
      run: export LC_ALL=en_US.utf8
      shell: bash

    - name: Collect jira issue numbers since last release/tag
      shell: bash
      id: jira-list
      run: |
        if [[ ${{ env.PATH_APP_NAME }} == channel ]]; then
          REGEX_APP_MERGE_COMMIT='\((channel|PWA)\):'
        elsif [[ ${{ env.PATH_APP_NAME }} == backoffice ]]; then
          REGEX_APP_MERGE_COMMIT='\((backoffice)\):'
        fi
        echo $REGEX_APP_MERGE_COMMIT
        REGEX_JIRA_TICKET=GHACT-[[:digit:]]{1,}
        echo $REGEX_JIRA_TICKET
        echo "ISSUES=$(git log --merges  $(git describe --abbrev=0 --tags)..HEAD | grep -iE $REGEX_APP_MERGE_COMMIT -B 2 | grep -oE $REGEX_JIRA_TICKET | uniq | sed 's/^\|$/"/g' | paste -sd , - | awk '{print $0}')" >> $GITHUB_ENV

    - name: Create json and invoke webhook
      run: |
        $json = ConvertTo-Json @{issues = @(${{ env.ISSUES }}); data = @{version = "${{ env.PATH_APP_NAME }}@v${{ env.VERSION }}"; projectName = "${{env.JIRA_PROJECT_KEY }}"}}
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-RestMethod ${{ inputs.jira-automation-webhook }} -Method Post -Body $json -ContentType "application/json"
      shell: pwsh
