name: Jira Release Web Hook
description: Creates a new Jira release and assigns all relevant issues to it.
inputs:
  jira-project-key:
    description: "Jira project identifier"
    required: true
  jira-automation-webhook:
    description: "Jira automation webhook url"
    required: true
  build-version:
    description: "Version identifier"
    required: true
runs:
  using: composite
  steps:
    - name: Update Locale
      run: export LC_ALL=en_US.utf8
      shell: bash

    - name: Collect issue numbers since last release/tag
      run: |
      if [[ ${{ env.APP_NAME }} == Channel ]]; then
        git log --merges  $(git describe --abbrev=0 --tags $(git describe --abbrev=0 --tags)^)..HEAD | grep -iE '\((Channel|PWA)\):' -B 2 | grep -oE "GHACT-[[:digit:]]{1,}" | uniq | awk '{print "RELATED_JIRA_ISSUES="$0}' >> $GITHUB_OUTPUT
      fi
      shell: bash

    - name: Create json and invoke webhook
      run: |
        $json = ConvertTo-Json @{issues = @(${{ RELATED_JIRA_ISSUES }}); data = @{version = "${{ env.VERSION }}"; projectName = "${{ inputs.jira-project-key }}"}}
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-RestMethod ${{ inputs.jira-automation-webhook }} -Method Post -Body $json -ContentType "application/json"
      shell: pwsh
