name: Package for Artifactory
description: create nuget package for pushing to artifactory
runs:
  using: composite
  steps:
    - name: Set Release Version
      shell: bash
      id: release-version
      run:
          echo "RELEASE_VERSION=${{ steps.package-version.outputs.VERSION }}+${{ env.APP_NAME }}" >> $GITHUB_OUTPUT

    - name: Get Last Release Version
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      id: last-release-version
      run: |
          echo "RELEASE_VERSION=$(gh release list | grep -i '^${{ env.PATH_APP_NAME }}@v' | head -n 1 | awk '{print $1}')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      env: 
        GH_TOKEN: ${{ github.token }}
      id: release-notes
      run: |
        COMMITS=$(node ./.github/release-notes/getCommits.js ${{ steps.last-release-version.outputs.RELEASE_VERSION }} | awk '{print $1}') >> $GITHUB_OUTPUT
