o name: Package for Artifactory
description: create nuget package for pushing to artifactory

runs:
  using: composite
  steps:

    - name: Bump ${{ env.APP_NAME }} Version
      shell: bash
      run: |
          npm version minor -w projects/${{ env.PATH_APP_NAME }}

    - name: Get Current Package Version
      shell: bash       
      id: package-version       
      run: |
        echo "VERSION=$(node -p "require('./projects/${{ env.PATH_APP_NAME }}/package.json').version")" >> $GITHUB_OUTPUT
        
    - name: Set Release Version
      shell: bash
      id: release-version
      run:
          echo "RELEASE_VERSION=${{ steps.package-version.outputs.VERSION }}+${{ env.APP_NAME }}" >> $GITHUB_OUTPUT

    - name: Commit Version Bump
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      run: |
        git pull origin master
        git commit -am "version(${{ env.APP_NAME }}): bump version to ${{ steps.package-version.outputs.VERSION }}" -nv
        git push -u origin master

    - name: Get Last Release Version
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      id: last-release-version
      run: |
          echo "LAST_VERSION=$(gh release list | grep -i '^${{ env.PATH_APP_NAME }}@v' | head -n 1 | awk '{print $1}')" >> $GITHUB_OUTPUT
    
    - name: Get App-specific commits since last App Release Version
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      env: 
        GH_TOKEN: ${{ github.token }}
      id: filtered-commits
      run: |
        node ./.github/release-notes/getCommits.js ${{ env.PATH_APP_NAME }} ${{ steps.last-release-version.outputs.LAST_VERSION }}

    - name: Create Release w/ Notes from Filtered Commit PR Titles
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      env: 
        GH_TOKEN: ${{ github.token }}
      id: release-notes
      run: |
        node ./.github/release-notes/createRelease.js ${{ env.PATH_APP_NAME }} ${{ steps.package-version.outputs.VERSION }} "${{ steps.filtered-commits.outputs.COMMITS }}"

    - name: Get Jira Issue IDs from App-specific PR Details
      if: env.DEPLOY_ENVIRONMENT == 'production'
      shell: bash
      id: pr-detail-jira-issues
      run: |
        node ./.github/jira-issues/getJiraIssues.js "${{ steps.filtered-commits.outputs.COMMITS }}" ${{ env.JIRA_PROJECT_NAME }}

    - name: Create json and invoke Jira webhook
      if: ${{ env.DEPLOY_ENVIRONMENT == 'production' && steps.pr-detail-jira-issues.outputs.JIRA_ISSUE_IDS != '' }}
      run: |
        $json = ConvertTo-Json @{issues = @("${{ steps.pr-detail-jira-issues.outputs.JIRA_ISSUE_IDS }}"); data = @{version = "${{ env.PATH_APP_NAME }}@v${{ steps.package-version.outputs.VERSION }}"; projectName = "${{ env.JIRA_PROJECT_NAME }}"}}
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-RestMethod ${{ env.JIRA_WEBHOOK_URL }} -Method Post -Body $json -ContentType "application/json"
      shell: pwsh
