
name: On Release Update Jira Issues

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Update Jira issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Jira issues with version
        uses: ./.github/actions/jira-release-update
        with:
          jira-project-key: 'GHACT'
          jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
          build-version: ${{ github.event.release.tag_name }}

  debug:
    name: Debugging Env
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
