
name: On Release Creation Update Jira Issues

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  debug:
      name: Debug
      runs-on: ubuntu-latest
      steps:
        - name: Dump env
          run: env | sort
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Jira issues with version
        uses: GeoWerkstatt/create-jira-release@v1
        with:
          jira-project-key: 'GHACT'
          jira-automation-webhook: ${{ secrets.JIRA_AUTOMATION_WEBHOOK }}
          build-version: v${{ github.event.release.tag_name }}
